// Mocks generated by Mockito 5.4.2 from annotations
// in manup/test/firebase_remote_config_man_up_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:manup/manup.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ConfigStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigStorage extends _i1.Mock implements _i2.ConfigStorage {
  MockConfigStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> storeFile({
    String? filename = r'man_up_config.json',
    required String? fileData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeFile,
          [],
          {
            #filename: filename,
            #fileData: fileData,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<String> readFile({String? filename = r'man_up_config.json'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readFile,
          [],
          {#filename: filename},
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}
