os:
  - linux
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - gem install coveralls-lcov
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1 .flutter
  - ./.flutter/bin/flutter doctor

script:
  - ./.flutter/bin/flutter pub get
  - ./.flutter/bin/flutter pub run build_runner build
  - ./.flutter/bin/flutter analyze
  - ./.flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov coverage/lcov.info
env:
  - DARTANALYZER_FLAGS=--fatal-warnings
cache:
  directories:
    - $HOME/.pub-cache
