name: manup
description: Mandatory update for Flutter Apps.
version: 1.0.0
homepage: https://github.com/NextFaze/flutter_manup

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.3.2
  pub_semver: ^1.4.2
  http: ^0.12.0
  meta: ^1.1.8
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0


flutter:
