name: manup
description: Mandatory update for Flutter Apps that prompts or forces app update by querying a hosted JSON file.
version: 4.0.2
homepage: https://github.com/NextFaze/flutter_manup

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^3.0.1
  pub_semver: ^2.1.2
  http: ^0.13.5
  meta: ^1.8.0
  url_launcher: ^6.1.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: any
