name: manup
description: Mandatory update for Flutter Apps.
version: 3.1.1
homepage: https://github.com/NextFaze/flutter_manup

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^1.0.1
  pub_semver: ^2.0.0
  http: ^0.13.3
  meta: ^1.7.0
  url_launcher: ^6.1.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  build_runner: any
