name: 🚀 Release to pub.dev

on: 
  workflow_dispatch:

jobs:
  job-release:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: 'Fetch packages'
      run: flutter pub get

    - name: Build generated files
      run: flutter pub run build_runner build

    - name: 'Analyze project'
      run: flutter analyze
      
    - name: 'Run tests'
      run: flutter test

    - name: 'Setup Credentials'
      run: |
        mkdir -p ~/.config/dart/
        cat <<EOF > ~/.config/dart/pub-credentials.json
          ${{ secrets.PUB_DEV_CREDENTIALS_JSON }}
        EOF

    - name: 'Publish'
      run: flutter pub publish -f