name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  job-release:
    permissions:
      id-token: write # This is required for authentication using OIDC
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: dart-lang/setup-dart@v1

      - name: 'Fetch packages'
        run: dart pub get

      - name: Build generated files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: 'Analyze project'
        run: flutter analyze

      - name: 'Run tests'
        run: flutter test

      - name: 'Publish'
        run: dart pub publish --force
